PADV-256 - Integrate current Sidebar MFE into the Learning Site.
Pearson-Advance/frontend-app-learning pull request #1
Opened 2022-12-09 17:27 UTC by anfbermudezme

WIP.

2022-12-14 01:17 UTC, alexjmpb commented on src/courseware/course/sidebar/SidebarTriggers.jsx
> +        }
```suggestion
```

What do you think about removing this condition and remove navigation from SIDEBAR_ORDER since is not longer being used in this wrapper?

2022-12-14 01:17 UTC, alexjmpb commented on src/courseware/course/sidebar/SidebarTriggerNavigation.jsx
> +    </div>
What do you think about make this element a component like "TriggerButton" so it can be used here and in sidebarTriggerNavigation?

2022-12-14 12:29 UTC, anfbermudezme commented on src/courseware/course/sidebar/SidebarTriggers.jsx
> +        }
Done !

2022-12-14 12:29 UTC, anfbermudezme commented on src/courseware/course/sidebar/SidebarTriggerNavigation.jsx
> +    </div>
Done !

2022-12-14 23:00 UTC, alexjmpb commented on src/courseware/course/sidebar/sidebars/navigation/NavigationSidebar.test.jsx
> +} from '../../../../../setupTest';
Couldn't absolute imports be used here?

2022-12-14 23:00 UTC, alexjmpb commented on src/courseware/course/sidebar/sidebars/navigation/NavigationTrigger.test.jsx
> +} from '../../../../../setupTest';
Same comment about absolute import here.

2022-12-15 03:49 UTC, Squirrel18 requested changes

2022-12-15 03:49 UTC, Squirrel18 commented on .env
> +NAVIGATION_MFE_BASE_URL=''
```suggestion
SIDEBAR_MFE_BASE_URL=''
```

2022-12-15 03:49 UTC, Squirrel18 commented on .github/workflows/validate.yml
> +on: [push, pull_request]
Please leave it as it is otherwise, CI would run every time we push any branch. @anfbermudezme

2022-12-15 12:00 UTC, anfbermudezme commented on src/courseware/course/sidebar/sidebars/navigation/NavigationSidebar.test.jsx
> +} from '../../../../../setupTest';
Done.

2022-12-15 12:00 UTC, anfbermudezme commented on src/courseware/course/sidebar/sidebars/navigation/NavigationTrigger.test.jsx
> +} from '../../../../../setupTest';
Done.

2022-12-16 14:27 UTC, alexjmpb approved these changes

2022-12-22 03:13 UTC, Squirrel18 approved these changes

2022-12-22 11:56 UTC, merged