PADV-526 - Learning MFE Migration.
Pearson-Advance/frontend-app-learning pull request #4
Opened 2023-06-01 22:03 UTC by anfbermudezme

## Ticket

https://agile-jira.pearson.com/browse/PADV-526

## Description

We will deploy the Learning (Courseware) MFE: https://github.com/openedx/frontend-app-learning/tree/open-release/olive.4 for the Olive migration.

## Type of Change

- [x] Cherry pick https://github.com/Pearson-Advance/frontend-app-learning/pull/1
- [x] Cherry pick https://github.com/Pearson-Advance/frontend-app-learning/pull/3

## Testing

- Use `make dev.up `to enable platform containers.
- Sign in in `localhost:18000`
- Go to `http://localhost:2000/course/your_course_key`.
- Test the Outline Sidebar Navigation.

2023-06-02 19:39 UTC, alexjmpb approved these changes

2023-06-06 16:57 UTC, Squirrel18 requested changes

2023-06-06 16:57 UTC, Squirrel18 commented on .github/workflows/validate.yml
> +    branches: [pearson-release/olive.master]
We don't have an "olive.master" branch. @anfbermudezme

2023-06-06 16:57 UTC, Squirrel18 commented on .github/workflows/validate.yml
> +    branches: [pearson-release/olive.master]
We don't have an "olive.master" branch. @anfbermudezme

2023-06-06 16:57 UTC, Squirrel18 commented on src/courseware/CoursewareContainer.jsx
> +      // Function to send the event to Outline Navigation SIdebar.
```suggestion
      // Function to send the event to Outline Navigation Sidebar.
```

2023-06-06 16:57 UTC, Squirrel18 commented on src/courseware/CoursewareContainer.jsx
> +      // Function to send the event to Outline Navigation SIdebar.
```suggestion
      // Function to send the event to Outline Navigation Sidebar.
```

2023-06-06 16:57 UTC, Squirrel18 commented on src/courseware/course/sidebar/TriggerButton.jsx
> +import { SIDEBARS } from './sidebars';
Why not use absolute imports? @anfbermudezme

2023-06-06 16:57 UTC, Squirrel18 commented on src/courseware/course/sidebar/sidebars/outline/OutlineSidebar.jsx
> +import messages from './messages';
Why not use absolute imports? @anfbermudezme

2023-06-07 00:28 UTC, Squirrel18 approved these changes

2023-06-07 01:20 UTC, merged